version: '3.3'

services:
  notion-mcp-gateway:
    image: node:18-alpine
    container_name: notion-mcp-gateway
    ports:
      - "8009:8009"
    environment:
      NOTION_API_TOKEN: "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"
      NOTION_MARKDOWN_CONVERSION: "true"
    command: sh -c "npx -y supergateway --stdio 'npx -y @suekou/mcp-notion-server' --port 8009 --baseUrl http://0.0.0.0:8009 --ssePath /sse --messagePath /message --cors --logLevel info"
    restart: unless-stopped

  github-mcp-gateway:
    image: node:18-alpine
    container_name: github-mcp-gateway
    ports:
      - "8010:8010"
    environment:
      GITHUB_PERSONAL_ACCESS_TOKEN: "${GITHUB_MCP_TOKEN}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "apk add --no-cache docker-cli && npx -y supergateway --stdio 'docker run -i --rm -e GITHUB_PERSONAL_ACCESS_TOKEN=$$GITHUB_PERSONAL_ACCESS_TOKEN ghcr.io/github/github-mcp-server' --port 8010 --baseUrl http://0.0.0.0:8010 --ssePath /sse --messagePath /message --cors --logLevel info"
    restart: unless-stopped

  agent-service:
    build:
      context: ./services/agent_service
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: agent-service
    ports:
      - "8000:8000"
    volumes:
      - ./services/agent_service/src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - github-mcp-gateway
      - notion-mcp-gateway

  data-ingestion-service:
    build:
      context: ./services/data_ingestion_service
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: data-ingestion-service
    ports:
      - "8003:8003"
    volumes:
      - ./services/data_ingestion_service/src:/app/src
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend-js
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:80"
    volumes:
      - ./frontend-js:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - agent-service
      - data-ingestion-service