version: '3.3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    ports:
      - "3001:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
